# Config file for the model of the neural network
import time
import numpy as np
from tensorboard.plugins.hparams import api as hp

INPUT_DIM = 4

HP_NUM_UNITS1 = hp.HParam('num_units1', hp.Discrete([32]))
HP_NUM_UNITS2 = hp.HParam('num_units2', hp.Discrete([32]))
HP_NUM_UNITS3 = hp.HParam('num_units3', hp.Discrete([32]))
HP_NUM_UNITS4 = hp.HParam('num_units4', hp.Discrete([32]))
HP_DROPOUT = hp.HParam('dropout', hp.Discrete([0.1]))
HP_OPTIMISER = hp.HParam('optimiser', hp.Discrete(['adam']))
HP_LR = hp.HParam('learning_rate', hp.Discrete([1e-3]))
HP_BATCH_SIZE = hp.HParam('batch_size', hp.Discrete([16]))
HP_MOMENTUM = hp.HParam('momentum', hp.Discrete([0.05]))
HP_REGULARISER_RATE = hp.HParam('regulariser_rate', hp.Discrete([0.1]))
HP_ACTIVATION = hp.HParam('activation', hp.Discrete(['relu']))
HP_previous_games = hp.HParam('num', hp.Discrete([i for i in range(1, 7)]))
HP_combine = hp.HParam('combine', hp.Discrete(['append', 'diff']))
HP_norm = hp.HParam('norm', hp.Discrete(['min-max', 'ratio']))

default_columns = ['date', 'link', 'home team', 'away team', 'home score', 'away score', 'league', 'season']

COLUMNS = {'elo only': default_columns + ['home elo', 'away elo'],

           'both andrew': default_columns + ['home pi rating', 'away pi rating', 'home elo',
                                             'away elo', 'home total shots',
                                             'away total shots', 'home shots on target', 'away shots on target'],

           'pi-rating only': default_columns +
                             ['home pi rating', 'away pi rating'],

           'both all': default_columns + ['home total shots',
                                          'away total shots',
                                          'home shots on target', 'away shots on target', 'home possession',
                                          'away possession',
                                          'home total conversion rate',
                                          'away total conversion rate', 'home fouls', 'away fouls',
                                          'home yellow cards',
                                          'away yellow cards',
                                          'home red cards', 'away red cards', 'home total passes',
                                          'away total passes',
                                          'home accurate passes',
                                          'away accurate passes', 'home open play conversion rate',
                                          'away open play conversion rate',
                                          'home set piece conversion', 'away set piece conversion',
                                          'home counter attack shots',
                                          'away counter attack shots',
                                          'home counter attack goals', 'away counter attack goals',
                                          'home key passes', 'away key passes',
                                          'home dribbles attempted', 'away dribbles attempted',
                                          'home dribble success',
                                          'away dribble success',
                                          'home aerials won%', 'away aerials won%', 'home tackles attempted',
                                          'away tackles attempted',
                                          'home tackles success %', 'away tackles success %', 'home was dribbled',
                                          'away was dribbled',
                                          'home interceptions',
                                          'away interceptions', 'home dispossessed', 'away dispossessed',
                                          'home errors', 'away errors', 'home pi rating', 'away pi rating', 'home elo',
                                          'away elo'],

           'everything both': default_columns + [
               'home total shots', 'away total shots', 'home total conversion rate',
               'away total conversion rate', 'home open play shots',
               'away open play shots',
               'home open play goals', 'away open play goals',
               'home open play conversion rate', 'away open play conversion rate',
               'home set piece shots', 'away set piece shots', 'home set piece goals',
               'away set piece goals', 'home set piece conversion',
               'away set piece conversion', 'home counter attack shots',
               'away counter attack shots', 'home counter attack goals',
               'away counter attack goals', 'home counter attack conversion',
               'away counter attack conversion', 'home penalty shots',
               'away penalty shots',
               'home penalty goals', 'away penalty goals', 'home penalty conversion',
               'away penalty conversion', 'home own goals shots',
               'away own goals shots',
               'home own goals goals', 'away own goals goals',
               'home own goals conversion',
               'away own goals conversion', 'home total passes', 'away total passes',
               'home total average pass streak', 'away total average pass streak',
               'home crosses', 'away crosses', 'home crosses average pass streak',
               'away crosses average pass streak', 'home through balls',
               'away through balls', 'home through balls average streak',
               'away through balls average streak', 'home long balls',
               'away long balls',
               'home long balls average streak', 'away long balls average streak',
               'home short  passes', 'away short  passes',
               'home short passes average streak', 'away short passes average streak',
               'home cards', 'away cards', 'home fouls', 'away fouls',
               'home unprofessional',
               'away unprofessional', 'home dive', 'away dive', 'home other',
               'away other',
               'home red cards', 'away red cards', 'home yellow cards',
               'away yellow cards',
               'home cards per foul', 'away cards per foul',
               'home woodwork', 'away woodwork', 'home shots on target',
               'away shots on target', 'home shots off target',
               'away shots off target',
               'home shots blocked', 'away shots blocked', 'home possession',
               'away possession', 'home touches', 'away touches',
               'home passes success',
               'away passes success',
               'home accurate passes', 'away accurate passes', 'home key passes',
               'away key passes', 'home dribbles won', 'away dribbles won',
               'home dribbles attempted', 'away dribbles attempted',
               'home dribbled past',
               'away dribbled past', 'home dribble success', 'away dribble success',
               'home aerials won', 'away aerials won', 'home aerials won%',
               'away aerials won%', 'home offensive aerials',
               'away offensive aerials',
               'home defensive aerials', 'away defensive aerials',
               'home successful tackles',
               'away successful tackles', 'home tackles attempted',
               'away tackles attempted',
               'home was dribbled', 'away was dribbled', 'home tackles success %',
               'away tackles success %', 'home clearances', 'away clearances',
               'home interceptions', 'away interceptions', 'home corners',
               'away corners',
               'home corner accuracy', 'away corner accuracy', 'home dispossessed',
               'away dispossessed', 'home errors', 'away errors', 'home offsides',
               'away offsides', 'home elo', 'away elo',
               'home pi rating',
               'away pi rating'],

           'pi-rating': default_columns + ['home total shots',
                                           'away total shots',
                                           'home shots on target', 'away shots on target', 'home possession',
                                           'away possession',
                                           'home total conversion rate',
                                           'away total conversion rate', 'home fouls', 'away fouls',
                                           'home yellow cards',
                                           'away yellow cards',
                                           'home red cards', 'away red cards', 'home total passes',
                                           'away total passes',
                                           'home accurate passes',
                                           'away accurate passes', 'home open play conversion rate',
                                           'away open play conversion rate',
                                           'home set piece conversion', 'away set piece conversion',
                                           'home counter attack shots',
                                           'away counter attack shots',
                                           'home counter attack goals', 'away counter attack goals',
                                           'home key passes', 'away key passes',
                                           'home dribbles attempted', 'away dribbles attempted',
                                           'home dribble success',
                                           'away dribble success',
                                           'home aerials won%', 'away aerials won%', 'home tackles attempted',
                                           'away tackles attempted',
                                           'home tackles success %', 'away tackles success %', 'home was dribbled',
                                           'away was dribbled',
                                           'home interceptions',
                                           'away interceptions', 'home dispossessed', 'away dispossessed',
                                           'home errors', 'away errors',
                                           'home home pi rating', 'home away pi rating', 'away home pi rating',
                                           'away away pi rating'
                                           ],
           'elo': default_columns + ['home total shots',
                                     'away total shots',
                                     'home shots on target', 'away shots on target', 'home possession',
                                     'away possession',
                                     'home total conversion rate',
                                     'away total conversion rate', 'home fouls', 'away fouls', 'home yellow cards',
                                     'away yellow cards',
                                     'home red cards', 'away red cards', 'home total passes', 'away total passes',
                                     'home accurate passes',
                                     'away accurate passes', 'home open play conversion rate',
                                     'away open play conversion rate',
                                     'home set piece conversion', 'away set piece conversion',
                                     'home counter attack shots',
                                     'away counter attack shots',
                                     'home counter attack goals', 'away counter attack goals', 'home key passes',
                                     'away key passes',
                                     'home dribbles attempted', 'away dribbles attempted', 'home dribble success',
                                     'away dribble success',
                                     'home aerials won%', 'away aerials won%', 'home tackles attempted',
                                     'away tackles attempted',
                                     'home tackles success %', 'away tackles success %', 'home was dribbled',
                                     'away was dribbled',
                                     'home interceptions',
                                     'away interceptions', 'home dispossessed', 'away dispossessed', 'home errors',
                                     'away errors',
                                     'home elo', 'away elo'
                                     ],

           'pi-rating+': default_columns + ['home total shots',
                                            'away total shots',
                                            'home shots on target', 'away shots on target', 'home possession',
                                            'away possession',
                                            'home total conversion rate',
                                            'away total conversion rate',
                                            'home pi rating', 'away pi rating'],
           'both': default_columns + ['home elo', 'away elo', 'home pi rating', 'away pi rating'],

           'both+': default_columns + ['home total shots',
                                       'away total shots',
                                       'home shots on target', 'away shots on target', 'home possession',
                                       'away possession', 'home accurate passes',
                                       'away accurate passes', 'home tackles attempted', 'away tackles attempted',
                                       'home tackles success %', 'away tackles success %', 'home was dribbled',
                                       'away was dribbled',
                                       'home interceptions',
                                       'away interceptions', 'home dispossessed', 'away dispossessed', 'home errors',
                                       'away errors',
                                       'home total conversion rate',
                                       'away total conversion rate', 'home elo', 'away elo', 'home pi rating',
                                       'away pi rating'],
           'both importance': default_columns + ['home accurate passes', 'home aerials won', 'home clearances',
                                                 'home corner accuracy', 'home corners',
                                                 'home crosses average pass streak', 'home dribbled past',
                                                 'home dribbles won', 'home elo', 'home errors', 'home interceptions',
                                                 'home key passes', 'home long balls average streak',
                                                 'home offensive aerials', 'home own goals conversion',
                                                 'home passes success', 'home pi rating', 'home possession',
                                                 'home score', 'home shots blocked', 'home shots on target',
                                                 'home tackles success %', 'home through balls average streak',
                                                 'home total average pass streak', 'home touches', 'home was dribbled',
                                                 'home woodwork', 'away accurate passes', 'away aerials won',
                                                 'away clearances', 'away corner accuracy', 'away corners',
                                                 'away crosses average pass streak', 'away dribbled past',
                                                 'away dribbles won', 'away elo', 'away errors', 'away interceptions',
                                                 'away key passes', 'away long balls average streak',
                                                 'away offensive aerials', 'away own goals conversion',
                                                 'away passes success', 'away pi rating', 'away possession',
                                                 'away score', 'away shots blocked', 'away shots on target',
                                                 'away tackles success %', 'away through balls average streak',
                                                 'away total average pass streak', 'away touches', 'away was dribbled',
                                                 'away woodwork'
                                                 ],
           'both k-importance': default_columns + ['home aerials won%', 'home clearances', 'home counter attack goals',
                                                   'home counter attack shots', 'home crosses average pass streak',
                                                   'home defensive aerials', 'home dispossessed',
                                                   'home dribble success', 'home dribbles attempted', 'home elo',
                                                   'home long balls average streak', 'home offensive aerials',
                                                   'home open play goals', 'home own goals conversion',
                                                   'home passes success', 'home pi rating', 'home possession',
                                                   'home score', 'home shots blocked', 'home successful tackles',
                                                   'home tackles attempted', 'home total conversion rate',
                                                   'home total shots', 'home unprofessional', 'home was dribbled',
                                                   'away aerials won%', 'away clearances', 'away counter attack goals',
                                                   'away counter attack shots', 'away crosses average pass streak',
                                                   'away defensive aerials', 'away dispossessed',
                                                   'away dribble success', 'away dribbles attempted', 'away elo',
                                                   'away long balls average streak', 'away offensive aerials',
                                                   'away open play goals', 'away own goals conversion',
                                                   'away passes success', 'away pi rating', 'away possession',
                                                   'away score', 'away shots blocked', 'away successful tackles',
                                                   'away tackles attempted', 'away total conversion rate',
                                                   'away total shots', 'away unprofessional', 'away was dribbled']}


def combination_of_means(teama_mean_array,
                         teamb_mean_array):  # How to combine the two means find the difference or put them all into the input
    mean_data_array = np.append(teama_mean_array, teamb_mean_array)
    # mean_data_array = teama_mean_array - teamb_mean_array
    return mean_data_array
